--/****** Object:  StoredProcedure [dbo].[AddPayment]    Script Date: 22/10/2020 11:36:58 ******/
--CREATE PROCEDURE [dbo].[AddPayment]
--  @fullname as nvarchar(50)
--  ,@Dob as datetime2(7)
--  ,@cardNumber as bigint
--  ,@cvc as smallint
--  ,@expiraryDate as datetime2(7)
--  ,@paymentId as uniqueidentifier
--  ,@currencyCode as nvarchar(3)
--  ,@amount as decimal(18,2)
--  ,@requestDate as datetime2(7)
--  ,@StatusId as int
--AS
--begin tran
--  begin try
--	  declare @userId as uniqueidentifier
--    declare @cardId as uniqueidentifier

--    if exists (select top(1) Id from [User] where Fullname = @fullname)
--    begin
--	    select top(1) @userId = Id from [User] where Fullname = @fullname
--    end
--    else
--    begin 
--	    INSERT INTO [dbo].[User]([Id],[Fullname])
--	    VALUES(NEWID(),@fullname)
--    end

--    if exists (select top(1) Id from [Card] where [CardNumber] = @cardNumber)
--    begin
--	    select top(1) @cardID = Id from [Card] where [CardNumber] = @cardNumber
--    end
--    else
--    begin 
--	    insert into [Card] ([Id],[CardNumber],[CVC],[ExpiryDate],[UserId])
--	    VALUES(NEWID(),@cardNumber,@cvc,@expiraryDate,@userId)
--    end

--    INSERT INTO [dbo].[Payment]
--               ([Id]
--               ,[CardId]
--               ,[CurrencyCode]
--               ,[Amount]
--               ,[RequestDate]
--               ,[Updated]
--               ,[StatusId])
--         VALUES
--               (@paymentId
--               ,@cardId
--               ,@currencyCode
--               ,@amount
--               ,@requestDate
--               ,GETUTCDATE()
--               ,@StatusId)
--    RETURN 0
--  commit tran
--end try
--begin catch
--  rollback tran
--  throw
--end catch