/*
 * Payment Gateway API
 *
 * Validates payment requests, stores card information, forwards payment requests and accepts responses from the acquiring bank.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using CheckoutPaymentGateway.Models;
using Microsoft.AspNetCore.Mvc;

namespace CheckoutPaymentGateway.Interfaces
{
	/// <summary>
	/// Handles creating and retrieving payments
	/// </summary>
	public interface IPaymentController
	{
		/// <summary>
		/// Generates a payment request with the gateway
		/// </summary>
		/// <remarks>Adds a payment</remarks>
		/// <param name="body">Payment to add</param>
		/// <response code="200">payment created</response>
		/// <response code="400">invalid input, object invalid</response>
		/// <response code="409">an existing payment already exists</response>
		IActionResult CreatePayment([FromBody] PaymentRequest body);
	}
}