/*
 * Payment Gateway API
 *
 * Validates payment requests, stores card information, forwards payment requests and accepts responses from the acquiring bank.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using CheckoutPaymentGateway.Models;
using Microsoft.AspNetCore.Mvc;

namespace CheckoutPaymentGateway.Interfaces
{
	public interface IPaymentController
	{
		IActionResult CreatePayment([FromBody] PaymentRequest body);
	}
}