:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore CheckoutPaymentGateway
dotnet build CheckoutPaymentGateway
echo Now, run the following to start the project: dotnet run -p CheckoutPaymentGateway\CheckoutPaymentGateway.csproj --launch-profile web.
echo.
