
global:
  scrape_interval:     10s # By default, scrape targets every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   monitor: 'nats-openrmf-server'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'checkoutpaymentgateway-read-prometheus'

    scheme: https
    # metrics_path defaults to '/metrics'
    static_configs:
    # replace the IP with your local IP for development
    # localhost is not it, as that is w/in the container :)
    - targets: ['checkoutpaymentgateway:443']
      #tls_config:
        #ca_file_path: "/etc/etcd/etcd-client-ca.crt"
        #cert_file_path: "/etc/etcd/etcd-client.crt"
        #key_file_path: "/etc/etcd/etcd-client.key"
      # tls_config:
        # ca_file_path: "/etc/etcd/etcd-client-ca.crt"
        # cert_file_path: "/etc/etcd/etcd-client.crt"
        # key_file_path: "/etc/etcd/etcd-client.key"
    #bearer_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQZXRlciI6IlB1bXB5IiwiZXhwIjoxNjk4NTc3NTI0LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo2MDAxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NjAwMSJ9.8_qyzWbfrw8CfAymD7gaZJk2bw83zNc_PxkC_7-8qUE
