/*
 * Payment Gateway API
 *
 * Validates payment requests, stores card information, forwards payment requests and accepts responses from the acquiring bank.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using CheckoutPaymentGateway.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CheckoutPaymentGateway.Interfaces
{
	/// <summary>
	/// Handles creating and retrieving payments
	/// </summary>
	public interface IPaymentController
	{
		/// <summary>
		/// Generates a payment request with the gateway
		/// </summary>
		/// <remarks>Adds a payment</remarks>
		/// <param name="body">Payment to add</param>
		/// <response code="200">payment created</response>
		/// <response code="400">invalid input, object invalid</response>
		/// <response code="409">an existing payment already exists</response>
		ActionResult<PaymentResponse> CreatePayment([FromBody] PaymentRequest body);

		/// <summary>
		/// Gets a payment information of a particualr request request 
		/// </summary>
		/// <remarks>Gets a payment</remarks>
		/// <param name="body">Payment to add</param>
		ActionResult<PaymentResponse> GetPayment([FromBody] Guid body);

		/// <summary>
		/// Reflects the string input. used to test if the service is up.
		/// </summary>
		/// <param name="echo"></param>
		/// <returns></returns>
		ActionResult<string> Echo(string echo);
	}
}