CREATE TABLE [dbo].[Card]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
		[CardNumber_encrypt] BIGINT NOT NULL, 
		[CVC_encrypt] INT NOT NULL, 
		[ExpiryDate] DATETIME2 NOT NULL, 
		[BankName] NVARCHAR(50) NOT NULL, 
		[UserId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Card_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
)
