/* 
 * Payment Gateway API
 *
 * Payment Gateway API (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
	/// <summary>
	///  Class for testing PaymentApi
	/// </summary>
	/// <remarks>
	/// This file is automatically generated by Swagger Codegen.
	/// Please update the test case below to test the API endpoint.
	/// </remarks>
	[TestFixture]
	public class PaymentApiTests
	{
		private PaymentApi instance;

		/// <summary>
		/// Setup before each unit test
		/// </summary>
		[SetUp]
		public void Init()
		{
			instance = new PaymentApi();
		}

		/// <summary>
		/// Clean up after each unit test
		/// </summary>
		[TearDown]
		public void Cleanup()
		{

		}

		/// <summary>
		/// Test an instance of PaymentApi
		/// </summary>
		[Test]
		public void InstanceTest()
		{
			Assert.IsInstanceOf(typeof(PaymentApi), instance, "instance is a PaymentApi");
		}

		/// <summary>
		/// Test CheckoutpaymentgatewayEchoGet
		/// </summary>
		[Test]
		public void CheckoutpaymentgatewayEchoGetTest()
		{
			string echo = null;
			var response = instance.CheckoutpaymentgatewayEchoGet(echo);
			Assert.IsInstanceOf<string>(response, "response is string");
		}
		/// <summary>
		/// Test CheckoutpaymentgatewayGetpaymentGet
		/// </summary>
		[Test]
		public void CheckoutpaymentgatewayGetpaymentGetTest()
		{
			Guid? body = null;
			var response = instance.CheckoutpaymentgatewayGetpaymentGet(body);
			Assert.IsInstanceOf<CheckoutPaymentGatewayModelsPaymentResponse>(response, "response is CheckoutPaymentGatewayModelsPaymentResponse");
		}
		/// <summary>
		/// Test CheckoutpaymentgatewayPaymentrequestPost
		/// </summary>
		[Test]
		public void CheckoutpaymentgatewayPaymentrequestPostTest()
		{
			CheckoutPaymentGatewayModelsPaymentRequest body = null;
			var response = instance.CheckoutpaymentgatewayPaymentrequestPost(body);
			Assert.IsInstanceOf<CheckoutPaymentGatewayModelsPaymentResponse>(response, "response is CheckoutPaymentGatewayModelsPaymentResponse");
		}
	}

}
